// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbyzd-qxkP_oD7eKi8wJraskdxGR0-FeM',
    appId: '1:758291987998:web:e68796d7915b31ddc1380f',
    messagingSenderId: '758291987998',
    projectId: 'homework4-messageboard-app',
    authDomain: 'homework4-messageboard-app.firebaseapp.com',
    storageBucket: 'homework4-messageboard-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEVwIsbFauMo7jPynx6F9gAICR2DpnuAI',
    appId: '1:758291987998:android:8d06c06bcd3cdc14c1380f',
    messagingSenderId: '758291987998',
    projectId: 'homework4-messageboard-app',
    storageBucket: 'homework4-messageboard-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp6WG-nxLowvMwluXpqdDC_j8xnu3ZbfM',
    appId: '1:758291987998:ios:c207069a91ec6897c1380f',
    messagingSenderId: '758291987998',
    projectId: 'homework4-messageboard-app',
    storageBucket: 'homework4-messageboard-app.firebasestorage.app',
    iosBundleId: 'com.example.homework4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp6WG-nxLowvMwluXpqdDC_j8xnu3ZbfM',
    appId: '1:758291987998:ios:c207069a91ec6897c1380f',
    messagingSenderId: '758291987998',
    projectId: 'homework4-messageboard-app',
    storageBucket: 'homework4-messageboard-app.firebasestorage.app',
    iosBundleId: 'com.example.homework4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbyzd-qxkP_oD7eKi8wJraskdxGR0-FeM',
    appId: '1:758291987998:web:7fc0bf8154a19961c1380f',
    messagingSenderId: '758291987998',
    projectId: 'homework4-messageboard-app',
    authDomain: 'homework4-messageboard-app.firebaseapp.com',
    storageBucket: 'homework4-messageboard-app.firebasestorage.app',
  );
}
